name: Test NPM project (reusable)

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
      npm-command:
        required: true
        type: string

jobs:
  test-npm:
    defaults:
      run:
        working-directory: ${{ inputs.folder }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - run: npm install
    - run: npm run ${{ inputs.npm-command }}